# Generated by Django 5.2.1 on 2025-05-28 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apt_delivery_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='menu_item',
        ),
        migrations.RemoveField(
            model_name='ordermeal',
            name='menu_item',
        ),
    ]
