# Generated by Django 5.1.7 on 2025-04-30 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt_delivery_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='meal',
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('price', models.PositiveIntegerField(verbose_name='Стоимость')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apt_delivery_app.meal')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='apt_delivery_app.menu')),
            ],
            options={
                'verbose_name': 'Элемент меню',
                'verbose_name_plural': 'Элементы меню',
            },
        ),
    ]
