# Generated by Django 5.1.7 on 2025-04-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt_delivery_app', '0002_remove_menu_meal_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='meal',
            field=models.ManyToManyField(through='apt_delivery_app.MenuItem', to='apt_delivery_app.meal', verbose_name='Блюдо'),
        ),
    ]
