# Generated by Django 5.1.7 on 2025-04-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt_delivery_app', '0003_menu_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.PositiveIntegerField(null=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='quantity',
            field=models.PositiveIntegerField(null=True, verbose_name='Количество'),
        ),
    ]
