# Generated by Django 5.1.7 on 2025-05-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt_delivery_app', '0006_alter_menuitem_price_alter_menuitem_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.PositiveIntegerField(null=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='quantity',
            field=models.PositiveIntegerField(null=True, verbose_name='Количество'),
        ),
    ]
