# Generated by Django 5.2 on 2025-05-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt_delivery_app', '0008_alter_menuitem_price_alter_menuitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Оплачен'),
        ),
        migrations.AddField(
            model_name='order',
            name='qr_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='QR код для подтверждения'),
        ),
    ]
